### ISSUE TITLE
Importing archived NATS client version

### ISSUE THREAD

**Issue by prochac** [nats-io/not.go#1]
cannot use msg (type *"github.com/nats-io/nats.go".Msg) as type *"github.com/nats-io/go-nats".Msg in argument to not.NewTraceMsg

**Comment by Cingulara** [comment]
@ColinSullivan1 this looks like the not.go uses the older NATS client, not the newer referenced one. Is this going to get updated? Does the not.go just need to be updated to use the new "github.com/nats-io/nats.go" versus "github.com/nats-io/go-nats"?

**Comment by ColinSullivan1** [comment]
Resolved by #2
