### ISSUE TITLE
Binary carrier with json payload

### ISSUE THREAD

**Issue by 6ecuk** [nats-io/not.go#5]
Hi. There any workaround about JSON payload in nats and opentracing? Now, when I trying to send JSON with tracing. On the subscriber side, I got not valid JSON - because binary carrier added trace id before.

**Comment by bekha-io** [comment]
Hey! I've faced the same problem today. Any updates or solutions on this? @6ecuk 

Thank you!

**Comment by 6ecuk** [comment]
Hi,  i switched on  opentracing.HTTPHeaders

**Comment by bekha-io** [comment]
> Hi, i switched on opentracing.HTTPHeaders

Unfortunately, HTTPHeaders are not compatible to my case. I use NATS as communication service and the payload for communication messages is JSON.

I tried to go with TextMap, but still no success.

**Comment by 6ecuk** [comment]
I'm also used  NATS as communication service.  I just put  opentracing.HTTPHeaders  in Metadata field.
