### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by 6ecuk** [nats-io/not.go#6]
Unfortunately, the binary carrier is not safe and in the case when you have produced a message without tracing injection was handled by a subscriber with tracer extractor you can catch fatal error: runtime: out of memory. 
Related issue: https://github.com/jaegertracing/jaeger-client-go/issues/321
Example:
```
#Producer
nc.Publish("test", []byte(`"user_id":"49e3c5bb-9c84-4222-9650-30bdde4649a8"`)
```

```
#Subscriber
t := not.NewTraceMsg(msg)

// Extract the span context from the request message.
sc, err := tracer.Extract(opentracing.Binary, t)
if err != nil {
    log.Printf("Extract error: %v", err)
}
``` 
https://github.com/jaegertracing/jaeger-client-go/blob/ef8f5edb71dffedf02a69593a23bb2fae4e16dc4/propagation.go#L244
![issue_1](https://user-images.githubusercontent.com/8338314/78686359-9a5afc80-78fb-11ea-9f14-e47097797b85.png)
![issue_2](https://user-images.githubusercontent.com/8338314/78686445-b199ea00-78fb-11ea-9dcd-1b3a6e6d559e.png)

**Comment by 6ecuk** [comment]
Generic header support may fix these issues. We can split spanID and payload between headers and body. 
https://github.com/nats-io/nats.go/pull/560/

**Comment by derekcollison** [comment]
We are about to land official header support.

**Comment by derekcollison** [comment]
Also, is this a jaeger client issue or this client library?

**Comment by 6ecuk** [comment]
It's the jaeger client issue

**Comment by derekcollison** [comment]
Can we post an issue over there as well?

**Comment by 6ecuk** [comment]
There exist the issue https://github.com/jaegertracing/jaeger-client-go/issues/321

**Comment by derekcollison** [comment]
Perfect thanks.

**Comment by 6ecuk** [comment]
@derekcollison Is there any due of new(tag) version of NATS with the headers support?

**Comment by derekcollison** [comment]
We are still working through any issues but could tag one if needed. Or do you mean do a release?

**Comment by 6ecuk** [comment]
@derekcollison I waiting for the release to run a stable version on our stage env

**Comment by derekcollison** [comment]
ok but we do not have a released server that supports it, only nightly builds etc.

**Comment by 6ecuk** [comment]
@derekcollison is nats streaming server will be support headers too?

**Comment by derekcollison** [comment]
We do not have plans at this time. @kozlovic will make final call though. We do support them in JetStream.

**Comment by kozlovic** [comment]
No plan, but if they are to be supported by the streaming layer, should headers then not be part of the protobuf itself? But doing so, is different than having them at the core NATS layer, so not sure that applies to this issue.

**Comment by 6ecuk** [comment]
https://github.com/jaegertracing/jaeger-client-go/pull/529 fixed the problem
